### ISSUE TITLE
Site name stays in navigation bar

### ISSUE THREAD

**Issue by justinsaraceno** [obenland/the-bootstrap#20] opened 2012-07-05 16:03 UTC
From Appearance -> Themes -> Customize -> Theme Options there is is a checkbox for 'Add site name to navigation bar'.  De-selecting it does not save and the site name remains in the navigation bar in v. 1.7.1.  It was working correctly for me in the previous version.  Thank you!

**Comment by obenland** [comment] 2012-07-06 10:38
Hi Justin,

thanks for reporting the issue.

I can't reproduce it on the-bootstrap.obenland.it, though. Are you sure your caching settings or plugins do not interfere?

**Comment by justinsaraceno** [comment] 2012-07-06 14:53
Hello,
Yes, I am sure caching isn't an issue.  I've tried in Chrome, Safari, and Firefox.  I've even changed the other theme options like nav bar position & content on left/right and those changes took just fine.  Both the site name and search form on nav bar stay visible even if I uncheck them.  Once I uncheck them and go back in to theme options, they are checked again.

I only have 2 non-stock plugins; a sidebar 'About' plugin and SyntaxHighlighter Evolved.  Neither of those use the nav bar in any way.

I'll keep looking for a solution and will respond if I find one.  Thanks again!

**Comment by obenland** [comment] 2012-07-16 09:09
Does this issue still appear in 1.8.0?

**Comment by justinsaraceno** [comment] 2012-07-18 00:27
Yes, it still happens.  Using Chrome developer tools I can see admin-ajax.php is accepting form data with the_bootstrap_theme_options[navbar_site_name]":false and it returns a 200 HTTP response.  I'm no closer to figuring out why it's not saving the change.

**Comment by obenland** [comment] 2012-07-18 06:50
You save it through ajax?

**Comment by justinsaraceno** [comment] 2012-07-18 12:02
No, I save it through the regular web interface but dug in to the form post being made.

**Comment by obenland** [comment] 2012-07-18 12:45
Is this the code in `the_bootstrap_theme_options_validate()`?

`$output['navbar_site_name']    =   isset( $input['navbar_site_name'] );`

**Comment by obenland** [comment] 2012-08-24 10:54
I figured it out. Took me a good half day, though. Hate debugging AJAX!
It actually was the code in the validation callback. It'll be fixed in 2.0.0

**Closed as completed by obenland** 2012-08-24 10:54 UTC
